# Converts the markdown file in ./entries into LaTeX, then moves it to LaTeX dir
all: 
	$(MAKE) -C latex/

clean:
	$(MAKE) -C latex/ clean

# Deletes the autogenerated latex files.
delete: $(wildcard ./latex/entries/*.tex)
	rm $?
	$(MAKE) -C latex/ delete